require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'Gemfile.lock'
    - 'config.ru'
    - 'services/demo/**/*'

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 15
