apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: demo-app
    image: localhost:5000/demo-app:latest
    ports:
      - containerPort: 3000
        name: http-web-svc
        
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: endpoint
    protocol: TCP
    port: 3000
    targetPort: http-web-svc
