apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name:
      labels:
        app:
    spec:
      replicas: 3
      template:
        metadata:
          name:
          labels:
            app:
        spec:
          containers:
            - name:
              image:
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
      selector:
        matchLabels:
          app:
  - apiVersion: v1
    kind: Service
    metadata:
      name:
    spec:
      selector:
        app:
      ports:
        - port: 3000
      type: NodePort